image: "registry.gitlab.com/chipsneutrino/chips-net/chips-net:latest"

stages:
  - build
  - test
  - docs

build:
  stage: build
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - cd ./env/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/chipsneutrino/chips-net/chips-net:latest .
    - docker push $CI_REGISTRY/chipsneutrino/chips-net/chips-net:latest
  only:
    changes:
      - ./env/*

flake8:
  stage: test
  script:
    - source /opt/conda/bin/activate
    - source activate chips
    - flake8 --max-line-length=120 chipsnet/*.py

pytest:
  stage: test
  script:
    - source /opt/conda/bin/activate
    - source activate chips
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - pytest

pdoc:
  stage: docs
  script:
    - source /opt/conda/bin/activate
    - source activate chips
    - pdoc --html chipsnet -o ./doc --force
    - mkdir .public
    - cp -r ./doc/chipsnet/* .public
    - mv .public public
  artifacts:
    paths:
      - public
