name: chipsnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - tqdm=4.46.0
  - flake8=3.8.1
  - autopep8=1.5.2
  - pytest=5.4.2
  - pdoc3=0.7.2
  - dotmap=1.2.20
  - pyyaml=5.3.1
  - numpy=1.18.1
  - pandas=1.0.3
  - matplotlib=3.2.1
  - seaborn=0.10.1
  - mplhep=0.1.21
  - pydotplus=2.0.2
  - python-graphviz=0.14
  - jupyterlab=2.1.2
  - papermill=2.1.0
  - uproot=3.11.6
  - root_pandas=0.7.0
  - root=6.20.4
  - cudnn=7.6.5=cuda10.1_0
  - pip=20.1.1
  - pip:
    - tensorflow==2.2.0
    - tensorboard-plugin-profile==2.2.0
    - parameter-sherpa==1.0.6
    - tf-explain==0.2.1
    - particle==0.10.0
    - comet-ml==3.1.7
    - coffea==0.6.39