name: chipsnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - make
  - gcc_linux-64
  - gxx_linux-64
  - black
  - papermill
  - tqdm
  - pytest
  - pdoc3
  - dotmap
  - pyyaml
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - mplhep
  - pydotplus
  - python-graphviz
  - jupyterlab
  - uproot
  - cudnn=7.6.5=cuda10.1_0
  - scikit-learn
  - pip
  - pip:
    - tensorflow==2.3.0
    - tensorboard-plugin-profile==2.3.0
    - parameter-sherpa
    - tf-explain
    - particle
    - comet-ml
    - pytest-docstyle
    - pytest-flake8
    - pytest-black
    - pandarallel
