name: chipsnet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - make=4.3
  - gcc_linux-64=9.3.0
  - gxx_linux-64=9.3.0
  - black=20.8b1
  - pytest=6.1.2
  - pdoc3=0.8.1
  - dotmap=1.2.20
  - pyyaml=5.3.1
  - numpy=1.19.4
  - pandas=1.1.5
  - matplotlib=3.3.3
  - seaborn=0.11.0
  - mplhep=0.2.9
  - pydotplus=2.0.2
  - python-graphviz=0.15
  - jupyterlab=2.2.9
  - uproot=3.13.0
  - cudnn=7.6.5=cuda10.1_0
  - scikit-learn=0.23.2
  - pip
  - pip:
    - tensorflow==2.3.0
    - tensorboard-plugin-profile==2.3.0
    - parameter-sherpa==1.0.6
    - tf-explain==0.2.1
    - particle==0.14.0
    - pytest-docstyle==2.0.1
    - pytest-flake8==1.0.6
    - pytest-black==0.3.12
