task: "train"
exp:
    name: "explain_energy"
    output_dir: "./data/models/analysis/explain/"
    comet: False
data:
    input_dirs:
        - "./data/input/chips_1200/nuel_cccoh/"
        - "./data/input/chips_1200/nuel_ccdis/"
        - "./data/input/chips_1200/nuel_ccqel/"
        - "./data/input/chips_1200/nuel_ccres/"
        - "./data/input/chips_1200/nuel_ccmec/"
    channels: [1, 1, 1]
    seperate_channels: False
    img_size: [64, 64]
    augment: False
    aug_factor_mean: [0.0, 0.0, 0.0]
    aug_factor_sigma: [0.02, 0.02, 0.02]
    aug_abs_mean: [0.0, 0.0, 0.0]
    aug_abs_sigma: [0.0, 0.0, 0.0]
    aug_noise_mean: [0.0, 0.0, 0.0]
    aug_noise_sigma: [0.0, 0.0, 0.0]
model:
    type: "vgg"
    labels: ["t_nu_energy"]
    lr: 0.0002
    lr_decay: 0.5
    dense_units: 512
    dropout: 0.1
    filters: 64
    reco_pars: False
    se_ratio: 16
    learn_weights: False
    precision_policy: "mixed_float16"
    summarise: False
trainer:
    train_examples: 1280000
    val_examples: 32000
    test_examples: 32000
    batch_size: 128
    epochs: 15
    tb_update: 1000
    steps_per_epoch: -1
    es_monitor: "val_mae"
    es_delta: 10
    es_epochs: 5