task: "train"
exp:
    name: "numu_cc_energy"
    output_dir: "./data/models/"
    comet: False
data:
    input_dirs:
        - "./data/input/chips_1200/numu_cccoh/"
        - "./data/input/chips_1200/numu_ccdis/"
        - "./data/input/chips_1200/numu_ccqel/"
        - "./data/input/chips_1200/numu_ccres/"
        - "./data/input/chips_1200/numu_ccmec/"
    unstack: True
    channels: [1, 1, 1]
    augment: False
    cat_select: -1
    img_size: [64, 64]
model:
    type: "vgg"
    labels: ["t_nuEnergy"]
    lr: 0.0002
    lr_decay: 0.5
    dense_units: 512
    dropout: 0.2
    filters: 64
    reco_pars: True
    bottleneck: False
    se_ratio: 16
    learn_weights: False
    precision_policy: "float32"
    summarise: False
trainer:
    train_examples: 256000
    val_examples: 64000
    test_examples: 64000
    batch_size: 128
    epochs: 20
    tb_update: 1000
    steps_per_epoch: -1
    es_monitor: "val_mae"
    es_delta: 10
    es_epochs: 3
    
