task: "create"
create:
    input_dirs:
        - "/unix/chips/jtingey/prod/cosmics/map/chips_1200/"
    out_dir: "./analysis/inputs/chips_1200/cosmics/"  
    sample_type: 2
    val_frac: 0.01
    test_frac: 0.2
    join: 10
    all_maps: False
    parallel: True
    par_scale: [1250.0, 1250.0, 600.0, 1.0, 3.14159]