task: "study"
exp:
    name: "study_energy"
    output_dir: "./data/models/analysis/study/"
    comet: False
data:
    input_dirs:
        - "./data/input/chips_1200/nuel_ccqel_numuflux/"
        - "./data/input/chips_1200/nuel_ccmec_numuflux/"
    channels: [1, 1, 1]
    seperate_channels: True
    img_size: [64, 64]
    augment: False
    aug_factor_mean: [0.0, 0.0, 0.0]
    aug_factor_sigma: [0.0, 0.0, 0.0]
    aug_abs_mean: [0.0, 0.0, 0.0]
    aug_abs_sigma: [0.0, 0.0, 0.0]
    aug_noise_mean: [0.0, 0.0, 0.0]
    aug_noise_sigma: [0.0, 0.0, 0.0]
model:
    type: "vgg"
    labels: ["t_nu_energy", "t_lep_energy"]
    lr: 0.0002
    lr_decay: 0.5
    dense_units: 512
    dropout: 0.1
    filters: 64
    reco_pars: True
    se_ratio: 16
    learn_weights: False
    precision_policy: "mixed_float16"
    summarise: False
trainer:
    train_examples: 1280000
    val_examples: 64000
    test_examples: 32000
    batch_size: 128
    epochs: 5
    tb_update: 1000
    steps_per_epoch: -1
    es_monitor: "val_t_nu_energy_mae"
    es_delta: 10
    es_epochs: 5
study:
    trials: 50
    objective: "val_t_nu_energy_mae"
    context: ["val_t_lep_energy_mae"]
    data:
        seperate_channels: [True, False]
        augment: [False]
    model:
        lr: [0.00005, 0.001]
        lr_decay: [0.5, 0.5]
        dense_units: [512]
        dropout: [0.0, 0.25]
        filters: [64]
        reco_pars: [True]
        se_ratio: [0, 16]
        learn_weights: [True, False]
    trainer:
        batch_size: [64, 128, 256]