task: "study"
exp:
    name: "study_beam"
    output_dir: "./data/models/analysis/study/"
    comet: False
data:
    input_dirs:
        - "./data/input/chips_1200/numu_all_numuflux/"
        - "./data/input/chips_1200/nuel_all_numuflux/"
    channels: [1, 1, 1]
    seperate_channels: True
    img_size: [64, 64]
    augment: True
    aug_factor_mean: [0.0, 0.0, 0.0]
    aug_factor_sigma: [0.02, 0.02, 0.02]
    aug_abs_mean: [0.0, 0.0, 0.0]
    aug_abs_sigma: [0.0, 0.0, 0.0]
    aug_noise_mean: [0.0, 0.0, 0.0]
    aug_noise_sigma: [0.0, 0.0, 0.0]
model:
    type: "inception"
    labels: ["t_comb_cat", "t_cc_cat", "t_nc_cat", "t_el_count", "t_mu_count", "t_p_count", "t_cp_count", "t_np_count", "t_g_count"]
    lr: 0.0002
    lr_decay: 0.5
    dense_units: 512
    dropout: 0.1
    filters: 64
    reco_pars: True
    se_ratio: 16
    learn_weights: False
    precision_policy: "mixed_float16"
    summarise: False
trainer:
    train_examples: 1280000
    val_examples: 32000
    test_examples: 32000
    batch_size: 128
    epochs: 10
    tb_update: 1000
    steps_per_epoch: -1
    es_monitor: "val_t_comb_cat_accuracy"
    es_delta: 0.0001
    es_epochs: 2
study:
    trials: 50
    objective: "val_t_comb_cat_accuracy"
    context: ["val_t_cc_cat_accuracy", "val_t_nc_cat_accuracy"]
    data:
        seperate_channels: [True]
        augment: [True]
    model:
        lr: [0.00005, 0.001]
        lr_decay: [0.5, 0.5]
        dense_units: [255, 512]
        dropout: [0.0, 0.25]
        filters: [32, 64]
        reco_pars: [True, False]
        se_ratio: [0, 8, 16]
        learn_weights: [False]
    trainer:
        batch_size: [64, 128, 256]
