---
task: 'train'
exp: # Variables used to define the output directory
    name: "cosmic_very_long_unstacked"
    experiment_dir: "models/"
data: # Variables used to define the input data
    input_dirs: 
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_all/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_coh_cc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_coh_nc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_dis_cc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_dis_nc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_res_cc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_res_nc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_qel_cc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_qel_nc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_numu_all/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_numu_coh_cc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_numu_coh_nc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_numu_dis_cc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_numu_dis_nc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_numu_res_cc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_numu_res_nc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_numu_qel_cc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_numu_qel_nc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/cosmic_numu_all/chips_1200_sk1pe/"
    all_chan: False
    stack: False
    channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    rand: [0.05, 0.05, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    shift: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    img_size: [64, 64, 3]
    par_scale: [1250.0, 1250.0, 600.0, 1.0, 180.0]
    batch_size: 64
    train_examples: 25000
    val_examples: 500
    test_examples: 1000
model: # Variables used to build the model
    name: "cosmic"
    reco_pars: True
    lr: 0.0002
    lr_decay: 0.0
    dense_units: 512
    dropout: 0.2
    kernel_size: 3
    filters: 64
trainer: # Variables used by the trainer
    num_epochs: 3
    steps_per_epoch: -1
    es_delta: 0.0001
    es_epochs: 10
study: # We list the number of trials and then all the variables we want to tune
    trials: 50
    data:
        batch_size: [64]
        stack: [true]
    model:
        reco_pars: [true, False]
        lr: [0.00005, 0.001]
        lr_decay: [0.0, 0.0]
        dense_units: [512, 1028]
        dropout: [0.0, 0.5]
        kernel_size: [3]
        filters: [64, 128]
