task: "create"  # What is the task? (create, train, study)
create:
    input_dirs:  # The .root map directories from which to take input data
        - "/unix/chips/jtingey/production/beam_all/nuel/map/chips_1200/"
        - "/unix/chips/jtingey/production/beam_all/anuel/map/chips_1200/"
        - "/unix/chips/jtingey/production/beam_all/numu/map/chips_1200/"
        - "/unix/chips/jtingey/production/beam_all/anumu/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/cccoh/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/nccoh/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ccdis/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ncdis/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ccqel/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ncqel/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ccres/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ncres/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ccmec/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/cccoh/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/nccoh/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ccdis/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ncdis/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ccqel/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ncqel/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ccres/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ncres/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ccmec/map/chips_1200/"
        #- "/unix/chips/jtingey/production/cosmic_all/map/chips_1200/"
    # Output .tfrecords directory
    out_dir: "./data/input/chips_1200_all/flux/"  
    #out_dir: "./data/input/chips_1200_all/nuel_cccoh/"
    #out_dir: "./data/input/chips_1200_all/nuel_nccoh/"
    #out_dir: "./data/input/chips_1200_all/nuel_ccdis/"
    #out_dir: "./data/input/chips_1200_all/nuel_ncdis/"
    #out_dir: "./data/input/chips_1200_all/nuel_ccqel/"
    #out_dir: "./data/input/chips_1200_all/nuel_ncqel/"
    #out_dir: "./data/input/chips_1200_all/nuel_ccres/"
    #out_dir: "./data/input/chips_1200_all/nuel_ncres/"
    #out_dir: "./data/input/chips_1200_all/nuel_ccmec/"
    #out_dir: "./data/input/chips_1200_all/numu_cccoh/"
    #out_dir: "./data/input/chips_1200_all/numu_nccoh/"
    #out_dir: "./data/input/chips_1200_all/numu_ccdis/"
    #out_dir: "./data/input/chips_1200_all/numu_ncdis/"
    #out_dir: "./data/input/chips_1200_all/numu_ccqel/"
    #out_dir: "./data/input/chips_1200_all/numu_ncqel/"
    #out_dir: "./data/input/chips_1200_all/numu_ccres/"
    #out_dir: "./data/input/chips_1200_all/numu_ncres/"
    #out_dir: "./data/input/chips_1200_all/numu_ccmec/"
    #out_dir: "./data/input/chips_1200_all/cosmic/"
    split: 0.1  # Fraction of data to set aside for both validation and testing
    join: 10  # How many input .root map files to join together
    all_maps: True  # Should all hit maps be passed through to the .tfrecords file?
    parallel: True  # Should the creation process be done in parallel, using multiple threads?
    par_scale: [1250.0, 1250.0, 600.0, 1.0, 3.14159]  # Reco parameter scales [vtxX, vtxY, vtxZ, dirTheta, dirPhi]