---
# Standard data creation configuration file

# Define the run task to be 'create' 
task: 'create'

# The 'study' task requires 1 types of variable used to define the configuration
# - create: data creator input parameters

create:
    # The input 'production' directory
    in_dir: "/mnt/storage/jtingey/chips-net/data/input/beam_nuel_cccoh/chips_1200"
    # The input 'production' directory
    out_dir: "/mnt/storage/jtingey/chips-net/data/input/beam_nuel_cccoh_test/"
    # Fraction of data to set aside for both validation and testing
    split: 0.1
    # How many input .root map files to join together
    join: 5
    # Should all hit maps be passed through to the .tfrecords file?
    all_maps: True
    # Should the creation process be done in parallel, using multiple threads?
    parallel: True