---
# Standard data creation configuration file

# Define the run task to be "create" 
task: "create"

# The "create" task requires 1 types of variable used to define the configuration
# - create: data creator input parameters

create:
    input_dirs:
        - "./data/maps/chips_1200/beam_all_nuel/"
        - "./data/maps/chips_1200/beam_all_anuel/"
        - "./data/maps/chips_1200/beam_all_numu/"
        - "./data/maps/chips_1200/beam_all_anumu/"
        #- ./data/maps/chips_1200/beam_nuel_cccoh/
        #- ./data/maps/chips_1200/beam_nuel_nccoh/
        #- ./data/maps/chips_1200/beam_nuel_ccdis/
        #- ./data/maps/chips_1200/beam_nuel_ncdis/
        #- ./data/maps/chips_1200/beam_nuel_ccqel/
        #- ./data/maps/chips_1200/beam_nuel_ncqel/
        #- ./data/maps/chips_1200/beam_nuel_ccres/
        #- ./data/maps/chips_1200/beam_nuel_ncres/
        #- ./data/maps/chips_1200/beam_nuel_ccmec/
        #- ./data/maps/chips_1200/beam_numu_cccoh/
        #- ./data/maps/chips_1200/beam_numu_nccoh/
        #- ./data/maps/chips_1200/beam_numu_ccdis/
        #- ./data/maps/chips_1200/beam_numu_ncdis/
        #- ./data/maps/chips_1200/beam_numu_ccqel/
        #- ./data/maps/chips_1200/beam_numu_ncqel/
        #- ./data/maps/chips_1200/beam_numu_ccres/
        #- ./data/maps/chips_1200/beam_numu_ncres/
        #- ./data/maps/chips_1200/beam_numu_ccmec/
        #- "./data/maps/chips_1200/cosmic_all/"

    # The output data directory
    out_dir: "./data/input/chips_1200_all/beam_flux/"
    #out_dir: "./data/input/chips_1200_all/beam_uniform/"
    #out_dir: "./data/input/chips_1200_all/cosmic/"
    # Fraction of data to set aside for both validation and testing
    split: 0.1
    # How many input .root map files to join together
    join: 10
    # Should all hit maps be passed through to the .tfrecords file?
    all_maps: True
    # Should the creation process be done in parallel, using multiple threads?
    parallel: False
    # How to scale each of the reco parameters [vtxX, vtxY, vtxZ, dirTheta, dirPhi]
    par_scale: [1250.0, 1250.0, 600.0, 1.0, 180.0]