---
# Standard data creation configuration file

# Define the run task to be "create" 
task: "create"

# The "create" task requires 1 types of variable used to define the configuration
# - create: data creator input parameters

create:
    input_dirs:
        - "/unix/chips/jtingey/production/beam_all/nuel/map/chips_1200/"
        - "/unix/chips/jtingey/production/beam_all/anuel/map/chips_1200/"
        - "/unix/chips/jtingey/production/beam_all/numu/map/chips_1200/"
        - "/unix/chips/jtingey/production/beam_all/anumu/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/cccoh/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/nccoh/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ccdis/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ncdis/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ccqel/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ncqel/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ccres/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ncres/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_nuel/ccmec/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/cccoh/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/nccoh/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ccdis/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ncdis/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ccqel/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ncqel/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ccres/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ncres/map/chips_1200/"
        #- "/unix/chips/jtingey/production/beam_numu/ccmec/map/chips_1200/"
        #- "/unix/chips/jtingey/production/cosmic_all/map/chips_1200/"

    # The output data directory
    out_dir: "./data/input/chips_1200_all/beam_flux/"
    #out_dir: "./data/input/chips_1200_all/beam_uniform/"
    #out_dir: "./data/input/chips_1200_all/cosmic/"
    # Fraction of data to set aside for both validation and testing
    split: 0.1
    # How many input .root map files to join together
    join: 10
    # Should all hit maps be passed through to the .tfrecords file?
    all_maps: True
    # Should the creation process be done in parallel, using multiple threads?
    parallel: True
    # How to scale each of the reco parameters [vtxX, vtxY, vtxZ, dirTheta, dirPhi]
    par_scale: [1250.0, 1250.0, 600.0, 1.0, 3.14159]