---
data: # Variables used to load the data
    input_dirs: 
        - "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_qel_cc/chips_1200_sk1pe/"
    all_chan: True
    reduced: True
    channels: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0]
    r_spread: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    img_size: [64, 64, 3]
    par_scale: [1250.0, 1250.0, 600.0, 1.0, 180.0]
    batch_size: 64
    max_examples: 5000
model: # Variables used to build the models
    dir: "models"
    path: "cosmic_base"
    name: "parameter"
    parameter: "true_nuEnergy"
    lr: 0.0002
    dense_units: 256
    dropout: 0.0
    kernel_size: 3
    filters: 64
eval: # Variables used by the evaluator
    type: "classification"
    cuts:
        q: 500.0
        hough: 500.0
        theta: 0.7
        phi: 0.3
    weights:
        total:  1214186
        #nuel:   0.000048879753398
        #numu:   0.002113382196077
        #nc:     0.000710731860207
        #cosmic: 0.997127006190318
        nuel: 0.000105 #0.035
        numu: 0.001995 #0.665
        nc: 0.0009 #0.3
        cosmic: 0.997
        
        