---
# Standard model evaluation configuration file

# Define the run task to be 'evaluate' 
task: 'evaluate'

# The 'evaluate' task requires 3 types of variables used to define the configuration
# - data: the input data and how it should be used
# - models: the model to train
# - eval: how the trainer should run

data:
    # The directories from which to take input data
    input_dirs: 
        - "./data/input/beam_nuel_all/chips_1200_sk1pe/"
        - "./data/input/beam_numu_all/chips_1200_sk1pe/"
        - "./data/input/cosmic_numu_all/chips_1200_sk1pe/"
    # Should the data reader, create the full set of parameters from file?
    extra_vars: False
    # Does the input data contain all possible input channels?
    all_chan: False
    # Should the images be stacked into a single tensor?
    stack: True
    # Which channels should be active?
    channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    # How much should each channel be randomly scaled?
    rand: [0.05, 0.05, 0.05, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    # How much should each channel be randomly shifted?
    shift: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    # The input image size
    img_size: [64, 64, 3]
    # How to scale each of the reco parameters [vtxX, vtxY, vtxZ, dirTheta, dirPhi]
    par_scale: [1250.0, 1250.0, 600.0, 1.0, 180.0]

models:
    cosmic_classification:
        dir: "./data/output/cosmic_models/"
        path: "cosmic"
        name: "cosmic"
        reco_pars: True
        lr: 0.0002
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    beam_classification:
        dir: "./data/output/beam_models/"
        path: "beam_all_long" 
        name: "beam_all"  # [beam_all, beam_full_comb, beam_nu_nc_comb, beam_nc_comb, beam_multi, beam_all_inception]
        reco_pars: True
        lr: 0.0002
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_0_energy:
        dir: "./data/output/energy_models/"
        path: "nuel_qel_cc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_1_energy:
        dir: "./data/output/energy_models/"
        path: "nuel_res_cc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_2_energy:
        dir: "./data/output/energy_models/"
        path: "nuel_dis_cc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_3_energy:
        dir: "./data/output/energy_models/"
        path: "nuel_coh_cc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_4_energy:
        dir: "./data/output/energy_models/"
        path: "numu_qel_cc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_5_energy:
        dir: "./data/output/energy_models/"
        path: "numu_res_cc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_6_energy:
        dir: "./data/output/energy_models/"
        path: "numu_dis_cc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_7_energy:
        dir: "./data/output/energy_models/"
        path: "numu_coh_cc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_8_energy:
        dir: "./data/output/energy_models/"
        path: "nuel_qel_nc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_9_energy:
        dir: "./data/output/energy_models/"
        path: "nuel_res_nc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_10_energy:
        dir: "./data/output/energy_models/"
        path: "nuel_dis_nc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_11_energy:
        dir: "./data/output/energy_models/"
        path: "nuel_coh_nc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_12_energy:
        dir: "./data/output/energy_models/"
        path: "numu_qel_nc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_13_energy:
        dir: "./data/output/energy_models/"
        path: "numu_res_nc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_14_energy:
        dir: "./data/output/energy_models/"
        path: "numu_dis_nc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cat_15_energy:
        dir: "./data/output/energy_models/"
        path: "numu_coh_nc_nuEnergy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    cosmic_energy:
        dir: "./data/output/energy_models/"
        path: "cosmic_energy" 
        name: "parameter"
        parameter: "t_nuEnergy"
        reco_pars: True
        lr: 0.0001
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64

eval:
    output: "./data/output/eval_output/cvn_output.root"
    test_examples: 160000  # Make it a multiple of the batch size
    batch_size: 64
    make_dense: False
    steps_per_epoch: -1
    cuts:
        cosmic: 0.001
        q: 500.0
        hough: 500.0
        theta: 0.7
        phi: 0.3
    weights:
        total:  1214186
        nuel:   0.000065135681199
        numu:   0.002807858128483
        cosmic: 0.997127006190318
    