---
# Evaluation configuration, different to the others mainly listing the various trained models
# and input datasets etc...

data:
    img_size: [64, 64]
    channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

samples:
    beam_flux:
        input_dirs: 
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/cosmic/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/beam_flux/"
        all_chan: True
        unstack: False
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        augment: False
        rand: [.05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05]
        shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
        img_size: [64, 64]
        labels_to_inputs: False
    beam_uniform:
        input_dirs: 
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/cosmic/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/beam_uniform/"
        all_chan: True
        unstack: False
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        augment: False
        rand: [.05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05]
        shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
        img_size: [64, 64]
        labels_to_inputs: False

models:
    beam_flux:
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "beam_flux" 
        name: "multi_simple"
        labels: ["t_all_cat", "t_nuEnergy", "prim_p", "prim_cp", "prim_np"]  
        reco_pars: False
        lr: 0.0002
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
        precision_policy: "float32"
        summarise: False
    beam_uniform:
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "beam_uniform" 
        name: "multi_simple"
        labels: ["t_all_cat", "t_nuEnergy", "prim_p", "prim_cp", "prim_np"]  
        reco_pars: False
        lr: 0.0002
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
        precision_policy: "float32"
        summarise: False
    beam_uniform_long:
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "beam" 
        name: "multi_simple"
        labels: ["t_all_cat", "t_nuEnergy", "prim_p", "prim_cp", "prim_np"]  
        reco_pars: False
        lr: 0.0002
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
        precision_policy: "float32"
        summarise: False
    cosmic:
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "cosmic"
        name: "cosmic"
        labels: ["t_cosmic_cat"]
        reco_pars: False
        lr: 0.0002
        lr_decay: 0.0
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
        precision_policy: "float32"
        summarise: False

eval:
    output: "./data/output/evaluation_output.root"
    examples: 32000  # Make it a multiple of the batch size
    cuts:
        cosmic: 0.001
        q: 500.0
        h: 500.0
        theta: 0.7
        phi: 0.3
    weights: # 1200
        nuel:   0.00003202064566
        anuel:  0.00000208200747
        numu:   0.00276174709613
        anumu:  0.00006042213136
        cosmic: 0.99714372811940
        total:  1214165.85244438

    