data:
    img_size: [64, 64]
    unstack: True  # Should we split the channels into seperate images?
model:
    learn_weights: False
samples:
    v_c_flux:
        input_dirs: 
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/flux/"
        unstack: False
        channels: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        augment: False
        rand: [.05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05]
        shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
        img_size: [64, 64]
        cat_select: -1
    v_ct_flux:
        input_dirs: 
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/flux/"
        unstack: False
        channels: [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        augment: False
        rand: [.05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05]
        shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
        img_size: [64, 64]
        cat_select: -1
    o_ct_flux:
        input_dirs: 
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/flux/"
        unstack: False
        channels: [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        augment: False
        rand: [.05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05]
        shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
        img_size: [64, 64]
        cat_select: -1
    i_ct_flux:
        input_dirs: 
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/flux/"
        unstack: False
        channels: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0]
        augment: False
        rand: [.05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05]
        shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
        img_size: [64, 64]
        cat_select: -1
    v_cth_flux:
        input_dirs: 
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/flux/"
        unstack: True
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        augment: False
        rand: [.05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05]
        shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
        img_size: [64, 64]
        cat_select: -1
    v_cth_uniform:
        input_dirs: 
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_cccoh/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_nccoh/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ccdis/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ncdis/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ccqel/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ncqel/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ccres/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ncres/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ccmec/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_cccoh/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_nccoh/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ccdis/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ncdis/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ccqel/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ncqel/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ccres/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ncres/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ccmec/"
        unstack: False
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        augment: False
        rand: [.05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05]
        shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
        img_size: [64, 64]
        cat_select: -1
    v_cth_uniform_cos:
        input_dirs: 
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_cccoh/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_nccoh/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ccdis/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ncdis/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ccqel/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ncqel/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ccres/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ncres/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/nuel_ccmec/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_cccoh/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_nccoh/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ccdis/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ncdis/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ccqel/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ncqel/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ccres/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ncres/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/numu_ccmec/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/cosmic/"
        unstack: False
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        augment: False
        rand: [.05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05]
        shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
        img_size: [64, 64]
        cat_select: -1
    v_cth_flux_cos:
        input_dirs: 
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/flux/"
            - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/cosmic/"
        unstack: False
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        augment: False
        rand: [.05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05]
        shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
        img_size: [64, 64]
        cat_select: -1
models:
    t_all_cat_v_c_uniform:
        channels: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_all_cat_v_c_uniform" 
        type: "vgg"  
        labels: ["t_all_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_all_cat_v_ct_uniform:
        channels: [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_all_cat_v_ct_uniform" 
        type: "vgg"  
        labels: ["t_all_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_all_cat_o_ct_uniform:
        channels: [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_all_cat_o_ct_uniform" 
        type: "vgg"  
        labels: ["t_all_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_all_cat_i_ct_uniform:
        channels: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_all_cat_i_ct_uniform" 
        type: "vgg"  
        labels: ["t_all_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_all_cat_v_cth_uniform:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_all_cat_v_cth_uniform" 
        type: "vgg"  
        labels: ["t_all_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_all_cat_v_cth_flux:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_all_cat_v_cth_flux" 
        type: "vgg"  
        labels: ["t_all_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_comb_cat_v_cth_uniform:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_comb_cat_v_cth_uniform" 
        type: "vgg"  
        labels: ["t_comb_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_nu_nc_cat_v_cth_uniform:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_nu_nc_cat_v_cth_uniform" 
        type: "vgg"  
        labels: ["t_nu_nc_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_nc_cat_v_cth_uniform:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_nc_cat_v_cth_uniform" 
        type: "vgg"  
        labels: ["t_nc_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_comb_cat_v_cth_flux:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_comb_cat_v_cth_flux" 
        type: "vgg"  
        labels: ["t_comb_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_nu_nc_cat_v_cth_flux:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_nu_nc_cat_v_cth_flux" 
        type: "vgg"  
        labels: ["t_nu_nc_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_nc_cat_v_cth_flux:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_nc_cat_v_cth_flux" 
        type: "vgg"  
        labels: ["t_nc_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_cos_cat_v_cth_flux:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_cosmic_cat_v_cth_flux"
        type: "vgg"
        labels: ["t_cosmic_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    t_cos_cat_v_cth_uniform:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "t_cosmic_cat_v_cth_uniform"
        type: "vgg"
        labels: ["t_cosmic_cat"]  
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: False  
    multi_v_cth_flux:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "multi_v_cth_flux"
        type: "vgg"
        labels: ["t_all_cat", "prim_p", "prim_cp", "prim_np", "t_vtxX", "t_vtxY", "t_vtxZ"] 
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: True
        precision_policy: "float32"
        summarise: False  
    multi_v_cth_uniform:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "multi_v_cth_uniform"
        type: "vgg" 
        labels: ["t_all_cat", "prim_p", "prim_cp", "prim_np", "t_vtxX", "t_vtxY", "t_vtxZ"] 
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.2
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: True
        precision_policy: "float32"
        summarise: False
    mult_test:
        channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        dir: "/mnt/storage/jtingey/chips-net/data/models/"
        path: "train_thisisit"
        type: "vgg"
        labels: ["t_all_cat", "t_cosmic_cat", "t_int_type", "t_comb_cat", "t_nu_nc_cat"]
        lr: 0.0002
        lr_decay: 0.5
        dense_units: 512
        dropout: 0.1
        filters: 64
        reco_pars: False
        bottleneck: False
        se_ratio: 16
        learn_weights: False
        precision_policy: "float32"
        summarise: True
eval:
    output: "./data/output/analysis_output.root"
    examples: 32000
    cuts:
        cosmic: 0.001   # Cosmic classifier cut
        q:      600.0   # r_raw_total_digi_q cut
        h:      600.0   # r_first_ring_height cut
        theta:  0.65    # r_dirTheta cut
        phi:    0.25    # r_dirPhi cut
    weights:
        # chips_1200 detector
        nuel:   0.00003202064566
        anuel:  0.00000208200747
        numu:   0.00276174709613
        anumu:  0.00006042213136
        cosmic: 0.99714372811940
        total:  1214165.85244438
        # chips_1000 detector
        #nuel:   0.00002974799103
        #anuel:  0.00000193423768
        #numu:   0.00256573301963
        #anumu:  0.00005613369079
        #cosmic: 0.99734645106085
        #total:  1089103.64395438
        # chips_800 detector
        #nuel:   0.00002676062972
        #anuel:  0.00000173999711
        #numu:   0.00230807624024
        #anumu:  0.00005049661715
        #cosmic: 0.99761292651578
        #total:  968546.578321513
        # chips_600 detector
        #nuel:   0.00002250846505
        #anuel:  0.00000146351803
        #numu:   0.00194133149815
        #anumu:  0.00004247289223
        #cosmic: 0.99799222362654
        #total:  863638.956297674
        # chips_400 detector
        #nuel:   0.00001704846385
        #anuel:  0.00000110850448
        #numu:   0.00147041212187
        #anumu:  0.00003217001097
        #cosmic: 0.99847926089884
        #total:  760154.010964974
        # chips_275 detector
        #nuel:   0.00001265444000
        #anuel:  0.00000082280160
        #numu:   0.00109143217450
        #anumu:  0.00002387860145
        #cosmic: 0.99887121198245
        #total:  704071.258478269

    