---
data: # Variables used to load the data
    input_dirs: 
        - "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_all/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_numu_all/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/cosmic_numu_all/chips_1200_sk1pe/"
    all_chan: True
    reduced: True
    stack: True
    channels: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0]
    rand: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    shift: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    img_size: [64, 64, 3]
    par_scale: [1250.0, 1250.0, 600.0, 1.0, 180.0]
    batch_size: 64
    max_examples: 500
models: # Variables used to build the models
    cosmic:
        dir: "models"
        path: "cosmic_extra_samples_5_rand_stacked"
        name: "cosmic"
        lr: 0.0002
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
    beam:
        dir: "models"
        path: "beam_extra_samples_5_rand_stacked"
        name: "beam"
        lr: 0.0002
        dense_units: 512
        dropout: 0.2
        kernel_size: 3
        filters: 64
eval: # Variables used by the evaluator
    type: "combined"
    cuts:
        cosmic: 0.001
        q: 500.0
        hough: 500.0
        theta: 0.7
        phi: 0.3
    weights:
        total:  1214186
        nuel:   0.000065135681199
        numu:   0.002807858128483
        cosmic: 0.997127006190318
    