---
task: 'train'
exp: # Variables used to save the experiment
    name: "nuel_qel_cc_nuEnergy"
    experiment_dir: "models/"
data: # Variables used to load thata
    input_dirs: 
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_coh_cc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_coh_nc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_dis_cc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_dis_nc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_res_cc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_res_nc/chips_1200_sk1pe/"
        - "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_qel_cc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_nuel_qel_nc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_numu_coh_cc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_numu_coh_nc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_numu_dis_cc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_numu_dis_nc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_numu_res_cc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_numu_res_nc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_numu_qel_cc/chips_1200_sk1pe/"
        #- "/mnt/storage/jtingey/chips-cvn/data/beam_numu_qel_nc/chips_1200_sk1pe/"
    all_chan: False
    stack: True
    channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    rand: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    shift: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    img_size: [64, 64, 3]
    par_scale: [1250.0, 1250.0, 600.0, 1.0, 180.0]
    batch_size: 64
    train_examples: 2500
    val_examples: 250
    test_examples: 250
model: # Variables used in building the model
    name: "parameter"
    parameter: "t_nuEnergy"
    reco_pars: True
    lr: 0.0001
    lr_decay: 0.0
    dense_units: 512
    dropout: 0.2
    kernel_size: 3
    filters: 64
trainer: # Variables used by the trainer
    num_epochs: 20
    steps_per_epoch: -1
    es_delta: 10
    es_epochs: 5
study: # We list the number of trials and then all the variables we want to tune
    trials: 100
    data:
        batch_size: [64, 128]
        stack: [true, False]
    model:
        lr: [0.00005, 0.001]
        dense_units: [256, 512]
        dropout: [0.0, 0.5]
        kernel_size: [3, 5]
        filters: [32, 64, 128]
