task: "train"  # What is the task? (create, train, study)
exp:
    name: "nuel_ccqel_energy"  # Name of experiment
    output_dir: "./analysis/models/"  # Path to model output experiment directory
    comet: False  # Should we use comet to store the experiment online
data:
    input_dirs:  # The directories from which to take input data
        - "./analysis/inputs/chips_1200/nuel_ccqel_numuflux/"
        - "./analysis/inputs/chips_1200/nuel_ccmec_numuflux/"
    channels: [1, 1, 1]  # Which channels should be active?
    seperate_channels: True  # Should we split the channels into seperate images?
    img_size: [64, 64]  # The input image size
    augment: False  # Should we enable absolute and factor augmentation of the input images?
    aug_factor_mean: [0.0, 0.0, 0.0]  # Scale bin contents by a factor, mean
    aug_factor_sigma: [0.0, 0.0, 0.0]  # Scale bin contents by a factor, sigma
    aug_abs_mean: [0.0, 0.0, 0.0]  # Shift bin contents by an absolute value if > zero, mean
    aug_abs_sigma: [0.0, 0.0, 0.0]  # Shift bin contents by an absolute value if > zero, sigma
    aug_noise_mean: [0.0, 0.0, 0.0]  # Shift bin contents by an absolute value as though noise, mean
    aug_noise_sigma: [0.0, 0.0, 0.0]  # Shift bin contents by an absolute value as though noise, sigma
model:
    type: "vgg"  # (vgg, resnet, inception)
    labels: ["t_nu_energy", "t_lep_energy", "t_vtx_x", "t_vtx_y", "t_vtx_z", "t_vtx_t"]  # For energy estimation
    lr: 0.0002  # The initial learning rate
    lr_decay: 0.5  # Learning rate decay coefficient
    dense_units: 512  # Number of units to use in dense layers
    dropout: 0.1  # Dropout rate to use in dropout layers
    filters: 64  # Initial number of filters to use
    reco_pars: True  # Should the reco paramters be appended to final dense layer?
    se_ratio: 16  # Ratio for squeeze-exitation blocks, if zero they will not be used
    learn_weights: True  # If training multiple labels, should we use the custom weight learning layer?
    precision_policy: "mixed_float16"  # Should we use mixed precision 'mixed_float16' or normal 'float32'
    summarise: True  # Should we display a summary of the model when it is built?
trainer:
    train_examples: 320000  # Number of training examples to use
    val_examples: 64000  # Number of validation examples to use
    test_examples: 64000  # Nqumber of testing examples to use
    batch_size: 128  # Training batch size
    epochs: 5  # Number of epochs to train for
    tb_update: 1000  # How often should tensorboard record values (batches)
    steps_per_epoch: -1  # Number of steps per epoch (-1 default)
    es_monitor: "val_t_nu_energy_mae"  # Metric to monitor for early stopping
    es_delta: 2  # Early stopping minimum delta value
    es_epochs: 5  # Early stopping epochs without delta change before stop