task: "train"
exp:
    name: "cosmic_v_ct"
    output_dir: "./data/models/"
    comet: False
data:
    input_dirs:
        - "./data/input/chips_1200_all/flux/"
        - "./data/input/chips_1200_all/cosmic/"
    unstack: True
    channels: [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    augment: True
    rand: [.02, .02, .02, .02, .02, .02, .02, .02, .02, .02, .02, .02, .02, .02, .02, .02, .02, .02, .02]
    shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
    cat_select: -1
    img_size: [64, 64]
model:
    type: "vgg"
    labels: ["t_cosmic_cat"]
    lr: 0.0002
    lr_decay: 0.5
    dense_units: 512
    dropout: 0.2
    filters: 64
    reco_pars: True
    bottleneck: False
    se_ratio: 16
    learn_weights: False
    precision_policy: "float32"
    summarise: True
trainer:
    train_examples: 1280000
    val_examples: 64000
    test_examples: 64000
    batch_size: 128
    epochs: 10
    tb_update: 1000
    steps_per_epoch: -1
    es_monitor: "val_accuracy"
    es_delta: 0.00001
    es_epochs: 2
    
