exp:
    output_dir: "./data/models/analysis/"

data:
    seperate_channels: True
    img_size: [64, 64]
    augment: False

model:
    lr: 0.0002
    lr_decay: 0.5
    dense_units: 512
    dropout: 0.1
    filters: 64
    reco_pars: True
    se_ratio: 16
    learn_weights: False
    precision_policy: "mixed_float16"
    summarise: False

samples:
    # Different input representations
    v_c_flux:
        input_dirs: 
            - "./data/input/chips_1200/flux/"
            - "./data/input/chips_1200/cosmic/"
        channels: [1, 0, 0]
    v_ct_flux:
        input_dirs: 
            - "./data/input/chips_1200/flux/"
            - "./data/input/chips_1200/cosmic/"
        channels: [1, 1, 0]
    o_ct_flux:
        input_dirs:
            - "./data/input/chips_1200_all/flux/"
            - "./data/input/chips_1200_all/cosmic/"
        channels: [0, 0, 0, 1, 1, 0, 0]
    i_ct_flux:
        input_dirs:
            - "./data/input/chips_1200_all/flux/"
            - "./data/input/chips_1200_all/cosmic/"
        channels: [0, 0, 0, 0, 0, 1, 1]
    v_cth_flux:
        input_dirs: 
            - "./data/input/chips_1200/flux/"
            - "./data/input/chips_1200/cosmic/"
        channels: [1, 1, 1]

    # Different samples
    both:
        input_dirs: 
            - "./data/input/chips_1200/flux/"
            - "./data/input/chips_1200/nuel_cccoh/"
            - "./data/input/chips_1200/nuel_nccoh/"
            - "./data/input/chips_1200/nuel_ccdis/"
            - "./data/input/chips_1200/nuel_ncdis/"
            - "./data/input/chips_1200/nuel_ccqel/"
            - "./data/input/chips_1200/nuel_ncqel/"
            - "./data/input/chips_1200/nuel_ccres/"
            - "./data/input/chips_1200/nuel_ncres/"
            - "./data/input/chips_1200/nuel_ccmec/"
            - "./data/input/chips_1200/numu_cccoh/"
            - "./data/input/chips_1200/numu_nccoh/"
            - "./data/input/chips_1200/numu_ccdis/"
            - "./data/input/chips_1200/numu_ncdis/"
            - "./data/input/chips_1200/numu_ccqel/"
            - "./data/input/chips_1200/numu_ncqel/"
            - "./data/input/chips_1200/numu_ccres/"
            - "./data/input/chips_1200/numu_ncres/"
            - "./data/input/chips_1200/numu_ccmec/"
        channels: [1, 1, 1]
    both_cosmic:
        input_dirs: 
            - "./data/input/chips_1200/flux/"
            - "./data/input/chips_1200/nuel_cccoh/"
            - "./data/input/chips_1200/nuel_nccoh/"
            - "./data/input/chips_1200/nuel_ccdis/"
            - "./data/input/chips_1200/nuel_ncdis/"
            - "./data/input/chips_1200/nuel_ccqel/"
            - "./data/input/chips_1200/nuel_ncqel/"
            - "./data/input/chips_1200/nuel_ccres/"
            - "./data/input/chips_1200/nuel_ncres/"
            - "./data/input/chips_1200/nuel_ccmec/"
            - "./data/input/chips_1200/numu_cccoh/"
            - "./data/input/chips_1200/numu_nccoh/"
            - "./data/input/chips_1200/numu_ccdis/"
            - "./data/input/chips_1200/numu_ncdis/"
            - "./data/input/chips_1200/numu_ccqel/"
            - "./data/input/chips_1200/numu_ncqel/"
            - "./data/input/chips_1200/numu_ccres/"
            - "./data/input/chips_1200/numu_ncres/"
            - "./data/input/chips_1200/numu_ccmec/"
            - "./data/input/chips_1200/cosmic/"
        channels: [1, 1, 1]
    flux:
        input_dirs: 
            - "./data/input/chips_1200/flux/"
        channels: [1, 1, 1]
    flux_cosmic:
        input_dirs: 
            - "./data/input/chips_1200/flux/"
            - "./data/input/chips_1200/cosmic/"
        channels: [1, 1, 1]
    uniform:
        input_dirs: 
            - "./data/input/chips_1200/nuel_cccoh/"
            - "./data/input/chips_1200/nuel_nccoh/"
            - "./data/input/chips_1200/nuel_ccdis/"
            - "./data/input/chips_1200/nuel_ncdis/"
            - "./data/input/chips_1200/nuel_ccqel/"
            - "./data/input/chips_1200/nuel_ncqel/"
            - "./data/input/chips_1200/nuel_ccres/"
            - "./data/input/chips_1200/nuel_ncres/"
            - "./data/input/chips_1200/nuel_ccmec/"
            - "./data/input/chips_1200/numu_cccoh/"
            - "./data/input/chips_1200/numu_nccoh/"
            - "./data/input/chips_1200/numu_ccdis/"
            - "./data/input/chips_1200/numu_ncdis/"
            - "./data/input/chips_1200/numu_ccqel/"
            - "./data/input/chips_1200/numu_ncqel/"
            - "./data/input/chips_1200/numu_ccres/"
            - "./data/input/chips_1200/numu_ncres/"
            - "./data/input/chips_1200/numu_ccmec/"
        channels: [1, 1, 1]
    uniform_cosmic:
        input_dirs: 
            - "./data/input/chips_1200/nuel_cccoh/"
            - "./data/input/chips_1200/nuel_nccoh/"
            - "./data/input/chips_1200/nuel_ccdis/"
            - "./data/input/chips_1200/nuel_ncdis/"
            - "./data/input/chips_1200/nuel_ccqel/"
            - "./data/input/chips_1200/nuel_ncqel/"
            - "./data/input/chips_1200/nuel_ccres/"
            - "./data/input/chips_1200/nuel_ncres/"
            - "./data/input/chips_1200/nuel_ccmec/"
            - "./data/input/chips_1200/numu_cccoh/"
            - "./data/input/chips_1200/numu_nccoh/"
            - "./data/input/chips_1200/numu_ccdis/"
            - "./data/input/chips_1200/numu_ncdis/"
            - "./data/input/chips_1200/numu_ccqel/"
            - "./data/input/chips_1200/numu_ncqel/"
            - "./data/input/chips_1200/numu_ccres/"
            - "./data/input/chips_1200/numu_ncres/"
            - "./data/input/chips_1200/numu_ccmec/"
            - "./data/input/chips_1200/cosmic/"
        channels: [1, 1, 1]
    cosmic:
        input_dirs: 
            - "./data/input/chips_1200/cosmic/"
        channels: [1, 1, 1]
    nuel_cccoh:
        input_dirs: 
            - "./data/input/chips_1200/nuel_cccoh/"
        channels: [1, 1, 1]
    nuel_ccdis:
        input_dirs: 
            - "./data/input/chips_1200/nuel_ccdis/"
        channels: [1, 1, 1]
    nuel_ccqel:
        input_dirs: 
            - "./data/input/chips_1200/nuel_ccqel/"
        channels: [1, 1, 1]
    nuel_ccres:
        input_dirs: 
            - "./data/input/chips_1200/nuel_ccres/"
        channels: [1, 1, 1]
    nuel_ccmec:
        input_dirs: 
            - "./data/input/chips_1200/nuel_ccmec/"
        channels: [1, 1, 1]
    nuel_ccqelmec:
        input_dirs: 
            - "./data/input/chips_1200/nuel_ccqel/"
            - "./data/input/chips_1200/nuel_ccmec/"
        channels: [1, 1, 1]
    numu_cccoh:
        input_dirs: 
            - "./data/input/chips_1200/numu_cccoh/"
        channels: [1, 1, 1]
    numu_ccdis:
        input_dirs: 
            - "./data/input/chips_1200/numu_ccdis/"
        channels: [1, 1, 1]
    numu_ccqel:
        input_dirs: 
            - "./data/input/chips_1200/numu_ccqel/"
        channels: [1, 1, 1]
    numu_ccres:
        input_dirs: 
            - "./data/input/chips_1200/numu_ccres/"
        channels: [1, 1, 1]
    numu_ccmec:
        input_dirs: 
            - "./data/input/chips_1200/numu_ccmec/"
        channels: [1, 1, 1]
    numu_ccqelmec:
        input_dirs: 
            - "./data/input/chips_1200/numu_ccqel/"
            - "./data/input/chips_1200/numu_ccmec/"
        channels: [1, 1, 1]

    # Stacked with no reco parameters as input for tf_explain
    stacked_noreco:
        input_dirs: 
            - "./data/input/chips_1200/flux/"
        channels: [1, 1, 1]
        seperate_channels: False
        reco_pars: False

    # Different augmentations to study model resiliance
    flux_factor_10:
        input_dirs: 
            - "./data/input/chips_1200/flux/"
        channels: [1, 1, 1]
        augment: True
        aug_factor_mean: [0.1, 0.1, 0.1]
        aug_factor_sigma: [0.02, 0.02, 0.02]
        aug_abs_mean: [0.0, 0.0, 0.0]
        aug_abs_sigma: [0.0, 0.0, 0.0]
    flux_factor_20:
        input_dirs: 
            - "./data/input/chips_1200/flux/"
        channels: [1, 1, 1]
        augment: True
        aug_factor_mean: [0.2, 0.2, 0.2]
        aug_factor_sigma: [0.02, 0.02, 0.02]
        aug_abs_mean: [0.0, 0.0, 0.0]
        aug_abs_sigma: [0.0, 0.0, 0.0]
    flux_factor_50:
        input_dirs: 
            - "./data/input/chips_1200/flux/"
        channels: [1, 1, 1]
        augment: True
        aug_factor_mean: [0.5, 0.5, 0.5]
        aug_factor_sigma: [0.02, 0.02, 0.02]
        aug_abs_mean: [0.0, 0.0, 0.0]
        aug_abs_sigma: [0.0, 0.0, 0.0]

models:
    # Different input representations
    repr_v_c:
        path: "repr_v_c" 
        type: "vgg"
        labels: ["t_nu_nc_cat"]
        channels: [1, 0, 0]
    repr_v_ct:
        path: "repr_v_ct" 
        type: "vgg"
        labels: ["t_nu_nc_cat"]
        channels: [1, 1, 0]
    repr_o_ct:
        path: "repr_o_ct" 
        type: "vgg"
        labels: ["t_nu_nc_cat"]
        channels: [0, 0, 0, 1, 1, 0, 0]
    repr_i_ct:
        path: "repr_i_ct" 
        type: "vgg"
        labels: ["t_nu_nc_cat"]
        channels: [0, 0, 0, 0, 0, 1, 1]
    repr_v_cth:
        path: "repr_v_cth" 
        type: "vgg"
        labels: ["t_nu_nc_cat"]
        channels: [1, 1, 1]

    # Different training sample models
    sample_both:
        path: "repr_v_cth" 
        type: "vgg"
        labels: ["t_nu_nc_cat"]
        channels: [1, 1, 1]
    sample_flux:
        path: "sample_flux" 
        type: "vgg"
        labels: ["t_nu_nc_cat"]
        channels: [1, 1, 1]
    sample_uniform:
        path: "sample_uniform" 
        type: "vgg"
        labels: ["t_nu_nc_cat"]
        channels: [1, 1, 1]

    # Different categorisation models
    cat_t_final_cat:
        path: "cat_t_final_cat" 
        type: "vgg"
        labels: ["t_final_cat"]
        channels: [1, 1, 1]
    cat_t_all_cat:
        path: "cat_t_all_cat" 
        type: "vgg"
        labels: ["t_all_cat"]
        channels: [1, 1, 1]
    cat_t_comb_cat:
        path: "cat_t_comb_cat" 
        type: "vgg"
        labels: ["t_comb_cat"]
        channels: [1, 1, 1]
    cat_t_nu_nc_cat:
        path: "repr_v_cth" 
        type: "vgg"
        labels: ["t_nu_nc_cat"]
        channels: [1, 1, 1]
    cat_t_nc_cat:
        path: "cat_t_nc_cat" 
        type: "vgg"
        labels: ["t_nc_cat"]
        channels: [1, 1, 1]
    cat_split:
        path: "cat_split" 
        type: "vgg"
        labels: ["t_comb_cat", "t_cc_type", "t_nc_type"]
        channels: [1, 1, 1]
    cat_split_learn:
        path: "cat_split_learn" 
        type: "vgg"
        labels: ["t_comb_cat", "t_cc_type", "t_nc_type"]
        channels: [1, 1, 1]

    # Cosmic classification models, multitask test
    cosmic:
        path: "cosmic" 
        type: "vgg"
        labels: ["t_cosmic_cat"]
        channels: [1, 1, 1]  
    cosmic_vtx:
        path: "cosmic_vtx" 
        type: "vgg"
        labels: ["t_cosmic_cat", "t_vtx_x", "t_vtx_y", "t_vtx_z", "t_vtx_t"]
        channels: [1, 1, 1]
    cosmic_vtx_learn:
        path: "cosmic_vtx_learn" 
        type: "vgg"
        labels: ["t_cosmic_cat", "t_vtx_x", "t_vtx_y", "t_vtx_z", "t_vtx_t"]
        channels: [1, 1, 1]

    # Beam classification models, multitask test
    beam:
        path: "repr_v_cth" 
        type: "vgg"
        labels: ["t_nu_nc_cat"]
        channels: [1, 1, 1]    
    beam_primaries:
        path: "beam_primaries" 
        type: "vgg"
        labels: ["t_nu_nc_cat", "prim_p", "prim_cp", "prim_np"]
        channels: [1, 1, 1] 
    beam_primaries_learn:
        path: "beam_primaries_learn" 
        type: "vgg"
        labels: ["t_nu_nc_cat", "prim_p", "prim_cp", "prim_np"]
        channels: [1, 1, 1] 
        
    # Energy models
    energy:
        path: "energy" 
        type: "vgg"
        labels: ["t_nu_energy"]
        channels: [1, 1, 1]
    lepton:
        path: "lepton" 
        type: "vgg"
        labels: ["t_lep_energy"]
        channels: [1, 1, 1]
    energy_lepton:
        path: "energy_lepton" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    energy_lepton_learn:
        path: "energy_lepton_learn" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]

    # Different sample energy models
    nuel_cccoh_energy:
        path: "nuel_cccoh_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    nuel_ccdis_energy:
        path: "nuel_ccdis_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    nuel_ccqel_energy:
        path: "nuel_ccqel_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    nuel_ccres_energy:
        path: "nuel_ccres_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    nuel_ccmec_energy:
        path: "nuel_ccmec_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    nuel_ccqelmec_energy:
        path: "nuel_ccqelmec_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    numu_cccoh_energy:
        path: "numu_cccoh_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    numu_ccdis_energy:
        path: "numu_ccdis_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    numu_ccqel_energy:
        path: "numu_ccqel_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    numu_ccres_energy:
        path: "numu_ccres_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    numu_ccmec_energy:
        path: "numu_ccmec_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    numu_ccqelmec_energy:
        path: "numu_ccqelmec_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    nuel_cc_energy:
        path: "energy_lepton" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    numu_cc_energy:
        path: "numu_cc_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]
    nc_energy:
        path: "nc_energy" 
        type: "vgg"
        labels: ["t_nu_energy", "t_lep_energy"]
        channels: [1, 1, 1]

    # Explain model
    explain:
        path: "explain" 
        type: "vgg"
        labels: ["t_nu_nc_cat"]
        channels: [1, 1, 1]
        seperate_channels: False
        reco_pars: False

eval:
    examples: 64000
    cuts:
        cosmic: 0.001   # Cosmic classifier cut
        q:      150.0   # r_total_digi_q cut
        h:      150.0   # r_first_ring_height cut
        theta:  0.75    # r_dirTheta cut
        phi:    0.35    # r_dirPhi cut
    weights:
        # chips_1200 detector
        nuel:   0.00003202064566
        anuel:  0.00000208200747
        numu:   0.00276174709613
        anumu:  0.00006042213136
        cosmic: 0.99714372811940
        total:  1214165.85244438
        # chips_1000 detector
        #nuel:   0.00002974799103
        #anuel:  0.00000193423768
        #numu:   0.00256573301963
        #anumu:  0.00005613369079
        #cosmic: 0.99734645106085
        #total:  1089103.64395438
        # chips_800 detector
        #nuel:   0.00002676062972
        #anuel:  0.00000173999711
        #numu:   0.00230807624024
        #anumu:  0.00005049661715
        #cosmic: 0.99761292651578
        #total:  968546.578321513
        # chips_600 detector
        #nuel:   0.00002250846505
        #anuel:  0.00000146351803
        #numu:   0.00194133149815
        #anumu:  0.00004247289223
        #cosmic: 0.99799222362654
        #total:  863638.956297674
        # chips_400 detector
        #nuel:   0.00001704846385
        #anuel:  0.00000110850448
        #numu:   0.00147041212187
        #anumu:  0.00003217001097
        #cosmic: 0.99847926089884
        #total:  760154.010964974
        # chips_275 detector
        #nuel:   0.00001265444000
        #anuel:  0.00000082280160
        #numu:   0.00109143217450
        #anumu:  0.00002387860145
        #cosmic: 0.99887121198245
        #total:  704071.258478269