---
task: "train"
exp:
    name: "multi_simple_v_cth_uniform"
    output_dir: "/mnt/storage/jtingey/chips-net/data/models/analysis"
    comet: False
data:
    input_dirs:
        - "/mnt/storage/jtingey/chips-net/data/input/chips_1200_all/beam_uniform/"
    all_chan: True
    unstack: False
    channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    augment: False
    rand: [.05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05]
    shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
    img_size: [64, 64]
    labels_to_inputs: False
model: 
    name: "multi_simple"   
    labels: ["t_all_cat", "prim_p", "prim_cp", "prim_np", "t_vtxX", "t_vtxY", "t_vtxZ"] 
    reco_pars: False
    lr: 0.0002
    lr_decay: 0.0
    dense_units: 512
    dropout: 0.2
    kernel_size: 3
    filters: 64
    precision_policy: "float32"
    summarise: True
trainer:
    train_examples: 960000
    val_examples: 160000
    test_examples: 160000
    batch_size: 64
    epochs: 10
    tb_update: 1000
    steps_per_epoch: -1
    es_delta: 0.001
    es_epochs: 2