task: "train"
exp:
    name: "repr_v_cth"
    output_dir: "./data/models/analysis/"
    comet: False
data:
    input_dirs:
        - "./data/input/chips_1200/flux/"
        - "./data/input/chips_1200/nuel_cccoh/"
        - "./data/input/chips_1200/nuel_nccoh/"
        - "./data/input/chips_1200/nuel_ccdis/"
        - "./data/input/chips_1200/nuel_ncdis/"
        - "./data/input/chips_1200/nuel_ccqel/"
        - "./data/input/chips_1200/nuel_ncqel/"
        - "./data/input/chips_1200/nuel_ccres/"
        - "./data/input/chips_1200/nuel_ncres/"
        - "./data/input/chips_1200/nuel_ccmec/"
        - "./data/input/chips_1200/numu_cccoh/"
        - "./data/input/chips_1200/numu_nccoh/"
        - "./data/input/chips_1200/numu_ccdis/"
        - "./data/input/chips_1200/numu_ncdis/"
        - "./data/input/chips_1200/numu_ccqel/"
        - "./data/input/chips_1200/numu_ncqel/"
        - "./data/input/chips_1200/numu_ccres/"
        - "./data/input/chips_1200/numu_ncres/"
        - "./data/input/chips_1200/numu_ccmec/"
    channels: [1, 1, 1]
    seperate_channels: True
    img_size: [64, 64]
    augment: True
    aug_factor_mean: [0.0, 0.0, 0.0]
    aug_factor_sigma: [0.02, 0.02, 0.02]
    aug_abs_mean: [0.0, 0.0, 0.0]
    aug_abs_sigma: [0.0, 0.0, 0.0]
model:
    type: "vgg"
    labels: ["t_nu_nc_cat"]
    lr: 0.0002
    lr_decay: 0.5
    dense_units: 512
    dropout: 0.1
    filters: 64
    reco_pars: True
    se_ratio: 16
    learn_weights: False
    precision_policy: "mixed_float16"
    summarise: False
trainer:
    train_examples: 1280000
    val_examples: 32000
    test_examples: 32000
    batch_size: 128
    epochs: 10
    tb_update: 1000
    steps_per_epoch: -1
    es_monitor: "val_accuracy"
    es_delta: 0.0001
    es_epochs: 2