task: "train"
exp:
    name: "t_cosmic_cat_v_cth_uniform"
    output_dir: "/mnt/storage/jtingey/chips-net/data/models/"
    comet: False
data:
    input_dirs:
        - "./data/input/chips_1200_all/beam_uniform/"
        - "./data/input/chips_1200_all/cosmic/"
    all_chan: True
    unstack: False
    channels: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    augment: False
    rand: [.05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05, .05]
    shift: [.0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0, .0]
    cat_select: -1
    img_size: [64, 64]
model:
    type: "vgg"
    labels: ["t_cosmic_cat"]
    lr: 0.0002
    lr_decay: 0.5
    dense_units: 512
    dropout: 0.2
    filters: 64
    reco_pars: False
    bottleneck: False
    se_ratio: 16
    learn_weights: False
    precision_policy: "float32"
    summarise: True   
trainer:
    train_examples: 960000
    val_examples: 160000
    test_examples: 160000
    batch_size: 64
    epochs: 10
    tb_update: 1000
    steps_per_epoch: -1
    es_monitor: "val_accuracy"
    es_delta: 0.0001
    es_epochs: 3
