#! /bin/bash

rm -rf data/input/chips_1200_all/flux
rm -rf data/input/chips_1200_all/nuel_cccoh
rm -rf data/input/chips_1200_all/nuel_nccoh
rm -rf data/input/chips_1200_all/nuel_ccdis
rm -rf data/input/chips_1200_all/nuel_ncdis
rm -rf data/input/chips_1200_all/nuel_ccqel
rm -rf data/input/chips_1200_all/nuel_ncqel
rm -rf data/input/chips_1200_all/nuel_ccres
rm -rf data/input/chips_1200_all/nuel_ncres
rm -rf data/input/chips_1200_all/nuel_ccmec
rm -rf data/input/chips_1200_all/numu_cccoh
rm -rf data/input/chips_1200_all/numu_nccoh
rm -rf data/input/chips_1200_all/numu_ccdis
rm -rf data/input/chips_1200_all/numu_ncdis
rm -rf data/input/chips_1200_all/numu_ccqel
rm -rf data/input/chips_1200_all/numu_ncqel
rm -rf data/input/chips_1200_all/numu_ccres
rm -rf data/input/chips_1200_all/numu_ncres
rm -rf data/input/chips_1200_all/numu_ccmec
rm -rf data/input/chips_1200_all/cosmic

rm -rf data/input/chips_1200/flux
rm -rf data/input/chips_1200/nuel_cccoh
rm -rf data/input/chips_1200/nuel_nccoh
rm -rf data/input/chips_1200/nuel_ccdis
rm -rf data/input/chips_1200/nuel_ncdis
rm -rf data/input/chips_1200/nuel_ccqel
rm -rf data/input/chips_1200/nuel_ncqel
rm -rf data/input/chips_1200/nuel_ccres
rm -rf data/input/chips_1200/nuel_ncres
rm -rf data/input/chips_1200/nuel_ccmec
rm -rf data/input/chips_1200/numu_cccoh
rm -rf data/input/chips_1200/numu_nccoh
rm -rf data/input/chips_1200/numu_ccdis
rm -rf data/input/chips_1200/numu_ncdis
rm -rf data/input/chips_1200/numu_ccqel
rm -rf data/input/chips_1200/numu_ncqel
rm -rf data/input/chips_1200/numu_ccres
rm -rf data/input/chips_1200/numu_ncres
rm -rf data/input/chips_1200/numu_ccmec
rm -rf data/input/chips_1200/cosmic