task: "create"
create:
    input_dirs:
        - "/unix/chips/jtingey/production/beam_all/nuel/map/chips_1200/"
        - "/unix/chips/jtingey/production/beam_all/anuel/map/chips_1200/"
        - "/unix/chips/jtingey/production/beam_all/numu/map/chips_1200/"
        - "/unix/chips/jtingey/production/beam_all/anumu/map/chips_1200/"
    out_dir: "./data/input/chips_1200_all/flux/"  
    split: 0.1
    join: 10
    all_maps: True
    parallel: True
    par_scale: [1250.0, 1250.0, 600.0, 1.0, 3.14159]