task: "create"
create:
    input_dirs:
        - "/unix/chips/jtingey/production/beam_numu/ccmec/map/chips_1200/"
    out_dir: "./data/input/chips_1200_all/numu_ccmec/"  
    split: 0.1
    join: 10
    all_maps: True
    parallel: True
    par_scale: [1250.0, 1250.0, 600.0, 1.0, 3.14159]