name: chips-cvn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pydot
  - flask
  - graphviz
  - jupyterlab
  - root 
  - root-binaries 
  - root-dependencies 
  - root_base
  - uproot
  - bunch
  - seaborn
  - cudatoolkit=10.1.243
  - cudnn=7.6.4=cuda10.1_0
  - flake8
  - pep8
  - autopep8
  - pytest
  - root_numpy
  - dotmap
  - pip
  - pip:
    - keras-vis
    - tensorflow
    - parameter-sherpa
    - comet_ml
